---
# myrepo
https://git.example.ch/exmaple/myrepo:
  command: uname
  gitlab_token: mysecret-myrepo
# test-repo
https://git.example.ch/exmaple/test-repo:
  command: uname
  gitlab_token: mysecret-test-repo
# quick command (no background, show output) and use payload as stdin
https://git.example.ch/example/test-repo:
  command: [ sh, -c, "jq . | sed 's/^/prefix /'" ]
  background: no
  gitlab_token:
# Run command by event
https://git.example.ch/example/test-repo1:
  commands:
    events:
      issue:
        command: [echo, "event issue received"]
      note:
        command: [echo, "event note received"]
  gitlab_token: mysecret-test-repo
# Run command main and command by event
https://git.example.ch/example/test-repo2:
  command: [echo, "prepare environment"]
  commands:
    events:
      issue:
        command: [echo, "event issue received"]
        note:
          command: [echo, "event note received"]
  gitlab_token: mysecret-test-repo